version: '3'
services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    networks:
      - '7940'
    ports:
      - 2181:2181
    environment: 
      - TZ=Asia/Shanghai

  
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    networks:
      - '7940'
    ports:
      - 5672:5672
      - 15672:15672
  
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["/usr/local/etc/redis/redis.conf"]
    networks:
      - '7940'

networks:
  '7940':
    name: '7940'
    driver: bridge